INSERT INTO categories VALUES (1, 'Mobile & Portable Radios');
INSERT INTO categories VALUES (2, 'Pagers');
INSERT INTO categories VALUES (3, 'Programs');
INSERT INTO categories VALUES (4, 'Repairs');
INSERT INTO categories VALUES (5, 'Speakers');
INSERT INTO categories VALUES (6, 'Accessories');
INSERT INTO categories VALUES (7, 'Antennas');
INSERT INTO categories VALUES (8, 'Assembly');
INSERT INTO categories VALUES (9, 'Batteries');
INSERT INTO categories VALUES (10, 'Cases');
INSERT INTO categories VALUES (11, 'Chargers');
INSERT INTO categories VALUES (12, 'Installs');
INSERT INTO categories VALUES (13, 'Microphones');
INSERT INTO categories VALUES (14, 'Other Equipment');
INSERT INTO categories VALUES (15, 'Combiners');
INSERT INTO categories VALUES (16, 'Combining Equipment');
INSERT INTO categories VALUES (17, 'Microwaves');
INSERT INTO categories VALUES (18, 'Multicoupliers');
INSERT INTO categories VALUES (19, 'Power Supplies');
INSERT INTO categories VALUES (20, 'Repeaters');
INSERT INTO categories VALUES (21, 'Brackets');
INSERT INTO categories VALUES (22, 'Battery Eliminators');
INSERT INTO categories VALUES (23, 'Digital Cameras');
INSERT INTO categories VALUES (24, 'Camcorders');
INSERT INTO categories VALUES (25, 'Speaker Microphones');
INSERT INTO categories VALUES (26, 'Radio Housing Kits');
INSERT INTO categories VALUES (27, 'Hands Free Kits');
INSERT INTO categories VALUES (28, 'Advance Communicators');
